{% set name = "dvc-webhdfs" %}
{% set version = "2.19.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fc438e40fe9c0b5cc213c0b0f8767f5bd5025397bc58fc61b097f86ae0028ff9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools_scm >=6.3.1
  run:
    - python >=3.8
    - dvc

test:
  imports:
    - dvc_webhdfs
  requires:
    - git
    - pip
  commands:
    - pip check
    - dvc version
    - dvc version | grep webhdfs

about:
  home: https://github.com/iterative/dvc-webhdfs
  summary: WebHDFS plugin for DVC
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - efiop
    - shcheklein
